#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Smacznego.Resource", IsApplication=true)]

namespace Smacznego
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slidefromright = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slidetoright = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Recipe_Types = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dodaj = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IkonaPrzepisu_danie = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IkonaPrzepisu_deser = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IkonaPrzepisu_napoj = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IkonaPrzepisu_weget = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IkonaPrzepisu_zupa = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int noimg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int noimgMini = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int AR_Layout = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int AR_dodajPrzepis = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int AR_nazwa = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int AR_przepis = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int AR_scroll = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int AR_skladniki = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int AR_title = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int AR_typ = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int DD_buttons = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int DD_cancel = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int DD_info = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int DD_layout = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int DD_ok = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int DD_title = 2131230729;
			
			// aapt resource value: 0x7f08001b
			public const int MA_ListaPrzepisow = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int MA_Pczysc = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int MA_Pdodaj = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int MA_layout = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int MA_logo = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int MA_menu = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int MA_poleszukaj = 2131230744;
			
			// aapt resource value: 0x7f080021
			public const int P_deleteRecipe = 2131230753;
			
			// aapt resource value: 0x7f08001c
			public const int P_layout = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int P_obrazek = 2131230750;
			
			// aapt resource value: 0x7f080023
			public const int P_przepis = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int P_scrollPrzepis = 2131230754;
			
			// aapt resource value: 0x7f08001f
			public const int P_scrollSklad = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int P_skladniki = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int P_title = 2131230749;
			
			// aapt resource value: 0x7f080013
			public const int ROW_Nazwa = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int ROW_Obrazek = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int ROW_Typ = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int SI_layout = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int SI_ok = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int SI_title = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int SI_whatneeded = 2131230736;
			
			// aapt resource value: 0x7f080024
			public const int spinerDropdownItem_text = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int spinnerItem_text = 2131230757;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialogAddRecipe = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialogDelete = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialogShowIngredients = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuGlowne = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Przepis = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int spinner_dropdown_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int spinner_item = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int AR_IgriError = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int AR_NameError = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int AR_RecipeError = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int AR_dodaj = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int AR_nazwa = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int AR_przepis = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int AR_skladniki = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int AR_title = 2131034115;
			
			// aapt resource value: 0x7f050015
			public const int DD_cancel = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int DD_info = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int DD_ok = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int DD_title = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int MA_Pczysc = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MA_app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int MA_wyszukaj = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int P_chooseImage = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int P_deleteRecipe = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int P_imageUpload = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int P_imageUploadComplete = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int P_imageUploadError = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int Recipe_Types = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int SI_ok = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int SI_title = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int databaseAdd = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int databaseAddError = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int databaseDeleteError = 2131034137;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
